### ISSUE TITLE
Text doesn't fit on buttons 

### ISSUE THREAD

**Issue by julyrashchenko** [dimitree54/expecto_patronum_library#23]
Because of this problem, sometimes it's not even clear what the button does.

Examples:
![Screenshot_20220815_152904_org.telegram.messenger.png](https://user-images.githubusercontent.com/54936869/184635191-b7545584-404f-427f-95f9-9c4648f172fb.png)
In this case there is 4 buttons. Maybe you can arrange them in a column not in a row? If it's not possible, the alternative idea is to write only numbers on the buttons, and add  identification for the numbers in the message above. Like: 
1 - make a wish
...

![Screenshot_20220815_153327_org.telegram.messenger.png](https://user-images.githubusercontent.com/54936869/184635796-997f2c0f-a2fb-4654-be8e-ebeafbec99ae.png)
On this case the third command description is not fully visible as well. I offer to make it shorter, maybe remove the words "your interlocutor", the message is still clear without them.

**Comment by dimitree54** [comment]
@julyrashchenko fixed, can you confirm that?

**Comment by julyrashchenko** [comment]
Confirm.
