### ISSUE TITLE
Confusing message when reporting

### ISSUE THREAD

**Issue by julyrashchenko** [dimitree54/expecto_patronum_library#24]
![Screenshot_20220815_153929_org.telegram.messenger.png](https://user-images.githubusercontent.com/54936869/184636629-26aad8b8-7be8-4336-a8c1-489c984207ca.png)
When I report my interlocutor, the bot writes that I was reported: it's a bit confusing.

**Comment by dimitree54** [comment]
Could you suggest better message? It is stored in bot_messages.properties/hotel_report

**Comment by dimitree54** [comment]
Message updated
