### ISSUE TITLE
Confusing scoring system 

### ISSUE THREAD

**Issue by julyrashchenko** [dimitree54/expecto_patronum_library#25]
![Screenshot_20220815_154220_org.telegram.messenger.png](https://user-images.githubusercontent.com/54936869/184637023-352a191c-0380-4a4f-9d44-0b0f0c56004f.png)
I created a task and I got -2, and then I canceled the task which I took for fulfillment and I got -4. I shouldn't have been fined for cancelling.

**Comment by dimitree54** [comment]
Fine for cancelling already matched task is an intended behaviour, because cancelling may be inconvenient for other party.
