### ISSUE TITLE
Reporting bug 

### ISSUE THREAD

**Issue by julyrashchenko** [dimitree54/expecto_patronum_library#26]
I reported a task which I took for fulfillment but it didn't disappear from my tasks
![Screenshot_20220815_161557.jpg](https://user-images.githubusercontent.com/54936869/184642682-e0bb5142-615d-40e6-8a56-05876e2e91b9.jpg)
![Screenshot_20220815_161712.jpg](https://user-images.githubusercontent.com/54936869/184642705-0003da3f-6f56-41fc-a4ab-077373d8dba5.jpg)

**Comment by dimitree54** [comment]
Fixed, @julyrashchenko can you test?

**Comment by dimitree54** [comment]
Fixed
