### ISSUE TITLE
Globally available tasks visibility

### ISSUE THREAD

**Issue by julyrashchenko** [dimitree54/expecto_patronum_library#27]
![Screenshot_20220815_162428_org.telegram.messenger.png](https://user-images.githubusercontent.com/54936869/184643592-9d9dff47-eaca-47e7-a58c-a8e1f00c497e.png)
Tasks that are globally available should be visible to the users that search for the tasks with the location: they also will be able to fulfill them. Also, if you don't fix it, there is the risk that these tasks will be noticed more rare than tasks with location because users will probably be providing location more often because this is one of the steps when you are up to take a task.

**Comment by dimitree54** [comment]
Fixed
